jobs:
  build_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: |
          export AWS_ACCESS_KEY_ID=<< parameters.aws_access_key_id >>
          export AWS_SECRET_ACCESS_KEY=<< parameters.aws_secret_key >>
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: aws s3 ls

workflows:
  version: 2
  execute_bulk:
    jobs:
      - build_deploy
