version: 2

jobs:
  build:
    docker:
      - image: amazon/aws-cli
        auth:
          username: mydockerhub-user
          aws_region: $AWS_REGION 
    steps:
      - run: echo $AWS_REGION
  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - run: echo $AWS_REGION

workflows:
  version: 2

  stage_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
