jobs:
  build_deploy:
    docker:
      - image: amazon/aws-cli:2.0.6
        auth: 
          AWS_ACCESS_KEY: $AWS_ACCESS_KEY
          AWS_REGION: $AWS_REGION
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run: |
          export AWS_ACCESS_KEY_ID=<< parameters.aws_access_key_id >>
          export AWS_SECRET_ACCESS_KEY=<< parameters.aws_secret_key >>
          name: Installing AWS CLI
          command: |
      - run: echo $AWS_ACCESS_KEY

workflows:
  version: 2
  execute_bulk:
    jobs:
      - build_deploy
