jobs:
  build_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: | 
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: aws s3 sync ./scripts s3://sftp.testing.bkt.9876

workflows:
  version: 2.
  execute_bulk:
    jobs:
      - build_deploy