version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.2

jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
      - run: aws s3 ls

workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
