jobs:
  build_deploy:
    docker:
      - image: ubuntu-2004:202010-01
        auth: 
          AWS_ACCESS_KEY: $AWS_ACCESS_KEY
          AWS_REGION: $AWS_REGION
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: aws s3 ls

workflows:
  version: 2
  execute_bulk:
    jobs:
      - build_deploy
