version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.2
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - aws-cli/setup:
          steps:
            - run: aws s3 ls
      - run: aws s3 ls
