version: 2

jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - run: echo $AWS_REGION
  deploy:
    docker:
      - image: circleci/python:latest
    steps:
      - run: echo $AWS_REGION

workflows:
  version: 2

  stage_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
